version: '3'

services:
  # Service for DVC pipeline
  dvc:
    build: .
    image: dvc_pipeline_image
    container_name: dvc_pipeline_container
    command: dvc repro -f # This will run the DVC pipeline
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # This will be read by docker-compose and passed to the container

  # Service for Flask application
  flask:
    build: .
    image: flask_api_image
    container_name: flask_api_container
    command: python src/flask_api.py  # This will run the Flask app
    volumes:
      - .:/app  # Mount the project directory to the container
    ports:
      - "5000:5000"  # Expose port 5000 for Flask app
    environment:
      - PYTHONUNBUFFERED=1  # Ensure unbuffered output for real-time logs
      - FLASK_ENV=production  # Set environment to production (no debug mode)

