version: '3.3'

services:
  # Service for DVC pipeline
  dvc:
    build: .
    image: dvc_pipeline_image
    env_file:
      - .env
    # environment:
    #   - DAGSHUB_USER_NAME=${DAGSHUB_USER_NAME}
    #   - DAGSHUB_PASSWORD=${DAGSHUB_PASSWORD}
    container_name: dvc_pipeline_container
    command: >
      sh -c "
      set -e &&
      
      (dvc remote list | grep . || { echo 'DVC remote list failed or no remotes found, checking config...'; exit 1; }) &&
      
      echo 'Authorization successful. Pulling the raw data from DagsHub repo ...' &&

      (dvc pull data/raw_data.csv 
      && echo 'The raw data was successfully pulled from the remote DagsHub repository.'
      || echo 'No raw data file found on DagsHub. No worries, the data will be downloaded from the Kaggle API'.) &&

      dvc repro -f &&
      dvc push
      "
    volumes:
      - .:/app

  # Service for Flask application
  flask:
    build: .
    image: flask_api_image
    container_name: flask_api_container
    depends_on:
      dvc:
        condition: service_completed_successfully

    command: python src/flask_api.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
