stages:
  download:
    cmd: python ${download_script_file}
    deps:
    - ${download_script_file}
    params:
    - download.kaggle_dataset
    - download.kaggle_file
    - download.download_folder
    - download.download_file
    outs:
    - ${download.download_folder}/${download.download_file}
  preprocess:
    cmd: python ${preprocess_script_file}
    deps:
    - ${preprocess_script_file}
    - ${download.download_folder}/${download.download_file} 
    params:
    - preprocess.input_folder
    - preprocess.input_file
    - preprocess.output_file_path
    - preprocess.rename_map
    - preprocess.keep_duplicates  
    outs:
    - ${preprocess.output_file_path}