stages:

  set_experiment_name:
    cmd: python ${set_experiment_name_script_file}
    deps:
    - ${set_experiment_name_script_file}
    outs:
    - ${mlflow_experiment_name_file_path}

  # create_dataset:
  #   cmd: python ${download_script_file}
  #   deps:
  #   - params.yaml
  #   - ${create_dataset}
  #   params:
  #    - create_dataset
  #   outs:
  #   - ${create_dataset.download_folder}/${download.download_file}

  preprocess:
    cmd: python ${preprocess_script_file}
    deps:
    - params.yaml
    - ${mlflow_experiment_name_file_path}
    - ${preprocess_script_file}
    - ${create_dataset.download_folder}/${create_dataset.download_file} 
    params:
    - preprocess 
    outs:
    - ${preprocess.output_reference_data_file_path}
    - ${preprocess.output_current_data_file_path}
    - ${preprocess.flask_dict_file_path}
    - ${preprocess.onehot_name_dictionary_file_path}

  train:
    cmd: python ${train_script_file}
    deps:
    - params.yaml
    - ${mlflow_experiment_name_file_path}
    - ${train_script_file}
    - ${preprocess.output_reference_data_file_path}     
    params:
    - train 
    outs:
    - ${train.test_X_file_path}
    - ${train.test_y_file_path}    
    - ${train.model_file_path}

  evaluate:
    cmd: python ${evaluate_script_file}
    deps:
    - params.yaml
    - ${mlflow_experiment_name_file_path}
    - ${evaluate_script_file}
    - ${preprocess.output_reference_data_file_path}    
    - ${train.test_y_file_path}    
    - ${train.model_file_path}
    params:
    - evaluate

  evidentlyai:
    cmd: python ${evidentlyai_script_file}
    deps:
    - params.yaml
    - ${mlflow_experiment_name_file_path}
    - ${evidentlyai_script_file}
    - ${preprocess.output_reference_data_file_path}
    - ${preprocess.output_current_data_file_path}
    params:
    - evidentlyai
    outs:
    - ${evidentlyai.evidently_htmls_folder_name}