stages:

  set_experiment_name:
    cmd: python ${set_experiment_name_script_file}
    deps:
    - ${set_experiment_name_script_file}
    outs:
    - ${mlflow_experiment_name_file_path}


  # # download_current_data:
  # #   cmd: python ${download_current_data_script_file}
  # #   deps: 
  # #     - ${download_current_data_script_file}
  # #   params:
  # #     - download_current_data
  # #   outs:
  # #     - ${download_current_data.data_folder}/${download_current_data.raw_current_data_file}:
  # #         cache: false  # Don't store in DVC cache


  preprocess:
    cmd: python ${preprocess_script_file}
    deps:
      - ${preprocess_script_file}
      - ${preprocess.data_folder}/${preprocess.input_file}
    params:
      - preprocess
    outs:
      - ${preprocess.data_folder}/${preprocess.output_file}
      # - ${preprocess.data_folder}/${preprocess.flask_dict_file}
      # - ${preprocess.data_folder}/${preprocess.onehot_name_dictionary_file}


  evidentlyai:
    cmd: python ${evidentlyai_script_file}
    deps:
    - ${evidentlyai_script_file}
    - ${evidentlyai.data_folder}/${evidentlyai.reference_data_file}
    - ${evidentlyai.data_folder}/${evidentlyai.reference_data_file}
    - ${evidentlyai.data_folder}/${evidentlyai.current_data_file}
    params:
    - evidentlyai
    outs:
    - ${evidentlyai.evidently_htmls_folder_name}


  merge_data:
    cmd: python ${merge_data_script_file}
    deps:
    - ${merge_data_script_file}
    - ${merge_data.data_folder}/${merge_data.preprocessed_reference_data_file}
    - ${merge_data.data_folder}/${merge_data.preprocessed_current_data_file}
    params:
    - merge_data
    outs:
    - ${merge_data.data_folder}/${merge_data.merged_data_file}


  train:
    cmd: python ${train_script_file}
    deps:
    - ${train_script_file}
    - ${train.data_folder}/${train.file}
    params:
    - train 
    outs:
    - ${train.data_folder}/${train.test_X_file}
    - ${train.data_folder}/${train.test_y_file}
    - ${train.new_model_file_path}


  evaluate:
    cmd: python ${evaluate_script_file}
    deps:
    - ${evaluate_script_file}
    - ${evaluate.data_folder}/${train.test_X_file}
    - ${evaluate.data_folder}/${train.test_y_file}
    params:
    - evaluate


  upload_predictions:
    cmd: python ${upload_predictions_script_file}
    deps:
    - ${upload_predictions_script_file}
    - ${upload_predictions.data_folder}/${upload_predictions.preprocessed_current_data_file}
    - ${upload_predictions.new_model_file_path}
    params:
    - upload_predictions
    outs:
    - ${upload_predictions.data_folder}/${upload_predictions.preprocessed_current_data_with_predictions_file}

  cleanup:
    cmd: python ${cleanup_script_file}
    deps:
    - ${cleanup_script_file}
    - dummy_file.txt
    params:
    - cleanup
