stages:

  set_experiment_name:
    cmd: python ${set_experiment_name_script_file}
    deps:
    - ${set_experiment_name_script_file}
    outs:
    - mlflow_experiment_name.yaml

  download:
    cmd: python ${download_script_file}
    deps:
    - params.yaml
    - ${download_script_file}
    params:
     - download
    outs:
    - ${download.download_folder}/${download.download_file}

  preprocess:
    cmd: python ${preprocess_script_file}
    deps:
    - params.yaml
    - ${preprocess_script_file}
    - ${download.download_folder}/${download.download_file} 
    params:
    - preprocess 
    outs:
    - ${preprocess.output_file_path}
    - ${preprocess.onehot_name_dictionary_file_path}

  train:
    cmd: python ${train_script_file}
    deps:
    - params.yaml
    - ${train_script_file}
    - ${preprocess.output_file_path}     
    params:
    - train 
    outs:
    - ${train.test_X_file_path}
    - ${train.test_y_file_path}    
    - ${train.model_file_path}

  evaluate:
    cmd: python ${evaluate_script_file}
    deps:
    - params.yaml
    - ${evaluate_script_file}
    - ${train.test_X_file_path}
    - ${train.test_y_file_path}    
    - ${train.model_file_path}
    params:
    - evaluate 
    #outs: