stages:

  download:
    cmd: python ${download_script_file}
    deps:
    - ${download_script_file}
    params:
     - download
    outs:
    - ${download.download_folder}/${download.download_file}

  preprocess:
    cmd: python ${preprocess_script_file}
    deps:
    - ${preprocess_script_file}
    - ${download.download_folder}/${download.download_file} 
    params:
    - preprocess 
    outs:
    - ${preprocess.output_file_path}

  train:
    cmd: python ${train_script_file}
    deps:
    - ${train_script_file}
    - ${preprocess.output_file_path}     
    params:
    - train 
    outs:
    - ${train.test_X_file_path}
    - ${train.test_y_file_path}    
    - ${train.model_file_path}
